# Generated by Django 5.2.3 on 2026-10-04 03:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countdown', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='countevent',
            name='notify',
            field=models.BooleanField(default=False, help_text='毎日0時に、これからの予定をまとめてメールで通知します。', verbose_name='メールで知らせる'),
        ),
        migrations.CreateModel(
            name='ReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_on', models.DateField(verbose_name='送信日')),
                ('event_count', models.PositiveSmallIntegerField(verbose_name='通知した予定の件数')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='送信日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='countdown_reminder_logs', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name_plural': 'Countdown リマインド送信記録',
                'ordering': ['-sent_on'],
                'constraints': [models.UniqueConstraint(fields=('user', 'sent_on'), name='countdown_reminder_once_per_day')],
            },
        ),
    ]
