# Generated by Django 5.2.3 on 2026-09-06 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveSmallIntegerField(unique=True, verbose_name='中分類番号')),
                ('name', models.CharField(max_length=40, verbose_name='中分類')),
                ('field', models.CharField(choices=[('T', 'テクノロジ系'), ('M', 'マネジメント系'), ('S', 'ストラテジ系')], max_length=1, verbose_name='分野')),
                ('major_code', models.PositiveSmallIntegerField(verbose_name='大分類番号')),
                ('major_name', models.CharField(max_length=40, verbose_name='大分類')),
                ('exam_weight', models.PositiveSmallIntegerField(verbose_name='科目A想定出題数')),
            ],
            options={
                'verbose_name': 'FE 中分類',
                'verbose_name_plural': 'FE 中分類',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='QuestionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True, verbose_name='テンプレートキー')),
                ('title', models.CharField(max_length=100, verbose_name='題材')),
                ('topic', models.CharField(blank=True, max_length=60, verbose_name='小分類')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='templates', to='fe.category', verbose_name='中分類')),
            ],
            options={
                'verbose_name': 'FE 問題テンプレート',
                'verbose_name_plural': 'FE 問題テンプレート',
                'ordering': ['category__code', 'key'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='再投入しても重複しないようにするための安定キー', max_length=60, unique=True, verbose_name='問題キー')),
                ('subject', models.CharField(choices=[('A', '科目A'), ('B', '科目B')], default='A', max_length=1, verbose_name='科目')),
                ('topic', models.CharField(blank=True, max_length=60, verbose_name='小分類')),
                ('stem', models.TextField(verbose_name='問題文')),
                ('choices', models.JSONField(verbose_name='選択肢')),
                ('answer_index', models.PositiveSmallIntegerField(verbose_name='正解の選択肢番号（0始まり）')),
                ('explanation', models.TextField(blank=True, verbose_name='解説')),
                ('difficulty', models.PositiveSmallIntegerField(choices=[(1, '基本'), (2, '標準'), (3, '応用')], default=2, verbose_name='難易度')),
                ('source', models.CharField(blank=True, max_length=120, verbose_name='出典・根拠')),
                ('params', models.JSONField(blank=True, null=True, verbose_name='生成パラメータ')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='fe.category', verbose_name='中分類')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='fe.questiontemplate', verbose_name='生成元テンプレート')),
            ],
            options={
                'verbose_name': 'FE 問題',
                'verbose_name_plural': 'FE 問題',
                'ordering': ['category__code', 'key'],
            },
        ),
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('focus', 'おまかせ（苦手を重点出題）'), ('random', '本番の出題比率どおり'), ('weak', '苦手分野だけ'), ('review', '間違えた問題の復習'), ('category', '分野を指定')], default='focus', max_length=10, verbose_name='出題モード')),
                ('subject', models.CharField(choices=[('A', '科目A'), ('B', '科目B')], default='A', max_length=1, verbose_name='科目')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fe.category', verbose_name='指定中分類')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fe_session', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'FE 出題設定',
                'verbose_name_plural': 'FE 出題設定',
            },
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_index', models.PositiveSmallIntegerField(verbose_name='選んだ選択肢')),
                ('is_correct', models.BooleanField(verbose_name='正誤')),
                ('elapsed_ms', models.PositiveIntegerField(blank=True, null=True, verbose_name='所要時間(ms)')),
                ('answered_at', models.DateTimeField(auto_now_add=True, verbose_name='解答日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fe_attempts', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='fe.category', verbose_name='中分類')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='fe.question', verbose_name='問題')),
            ],
            options={
                'verbose_name': 'FE 解答履歴',
                'verbose_name_plural': 'FE 解答履歴',
                'ordering': ['-answered_at'],
                'indexes': [models.Index(fields=['user', '-answered_at'], name='fe_attempt_user_id_38082c_idx'), models.Index(fields=['user', 'category'], name='fe_attempt_user_id_526886_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['subject', 'category'], name='fe_question_subject_26774d_idx'),
        ),
    ]
