# Generated by Django 5.2.3 on 2026-09-06 23:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fe', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='question',
            name='fe_question_subject_26774d_idx',
        ),
        migrations.AddField(
            model_name='question',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fe_questions', to=settings.AUTH_USER_MODEL, verbose_name='所有者'),
        ),
        migrations.AddField(
            model_name='question',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日時'),
        ),
        migrations.AlterField(
            model_name='question',
            name='key',
            field=models.CharField(max_length=60, verbose_name='問題キー'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['owner', 'subject', 'category'], name='fe_question_owner_i_e82c7f_idx'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(fields=('owner', 'key'), name='fe_unique_key_per_owner'),
        ),
    ]
