# Generated by Django 5.2.3 on 2026-09-06 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fe', '0003_question_owner_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='answer_index',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='正解の選択肢番号'),
        ),
        migrations.AddField(
            model_name='attempt',
            name='question_stem',
            field=models.TextField(blank=True, verbose_name='問題文（解答時点）'),
        ),
        migrations.AddField(
            model_name='attempt',
            name='question_topic',
            field=models.CharField(blank=True, max_length=60, verbose_name='小分類（解答時点）'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attempts', to='fe.question', verbose_name='問題'),
        ),
    ]
