# Generated by Django 5.2.3 on 2026-09-07 00:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def drop_orphan_attempts(apps, schema_editor):
    """問題が消えて宙に浮いた解答ログを取り除く。

    解答ログは問題と一緒に消える短期的な記録に戻すため、参照先の無い行は残さない。
    分野ごとの理解度は CategoryProgress に積み直されるので、実力の記録は失われない。
    """
    Attempt = apps.get_model('fe', 'Attempt')
    Attempt.objects.filter(question__isnull=True).delete()


def noop(apps, schema_editor):
    """巻き戻しでは何もしない。"""


class Migration(migrations.Migration):

    dependencies = [
        ('fe', '0004_attempt_keeps_snapshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('A', '科目A'), ('B', '科目B')], default='A', max_length=1, verbose_name='科目')),
                ('answered', models.PositiveIntegerField(default=0, verbose_name='解答数')),
                ('correct', models.PositiveIntegerField(default=0, verbose_name='正解数')),
                ('last_answered_at', models.DateTimeField(blank=True, null=True, verbose_name='最終解答日時')),
            ],
            options={
                'verbose_name': 'FE 分野別の理解度',
                'verbose_name_plural': 'FE 分野別の理解度',
                'ordering': ['category__code'],
            },
        ),
        migrations.CreateModel(
            name='DailyProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日付')),
                ('answered', models.PositiveIntegerField(default=0, verbose_name='解答数')),
                ('correct', models.PositiveIntegerField(default=0, verbose_name='正解数')),
            ],
            options={
                'verbose_name': 'FE 日別の学習記録',
                'verbose_name_plural': 'FE 日別の学習記録',
                'ordering': ['-date'],
            },
        ),
        migrations.AlterModelOptions(
            name='attempt',
            options={'ordering': ['-answered_at'], 'verbose_name': 'FE 解答ログ', 'verbose_name_plural': 'FE 解答ログ'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['category__code', 'id'], 'verbose_name': 'FE 問題', 'verbose_name_plural': 'FE 問題'},
        ),
        migrations.RemoveConstraint(
            model_name='question',
            name='fe_unique_key_per_owner',
        ),
        migrations.RemoveField(
            model_name='attempt',
            name='answer_index',
        ),
        migrations.RemoveField(
            model_name='attempt',
            name='question_stem',
        ),
        migrations.RemoveField(
            model_name='attempt',
            name='question_topic',
        ),
        migrations.RemoveField(
            model_name='question',
            name='key',
        ),
        migrations.RunPython(drop_orphan_attempts, noop),
        migrations.AlterField(
            model_name='attempt',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='fe.question', verbose_name='問題'),
        ),
        migrations.AddField(
            model_name='categoryprogress',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='progress', to='fe.category', verbose_name='中分類'),
        ),
        migrations.AddField(
            model_name='categoryprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fe_progress', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー'),
        ),
        migrations.AddField(
            model_name='dailyprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fe_daily_progress', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー'),
        ),
        migrations.AddConstraint(
            model_name='categoryprogress',
            constraint=models.UniqueConstraint(fields=('user', 'category', 'subject'), name='fe_unique_progress'),
        ),
        migrations.AddConstraint(
            model_name='dailyprogress',
            constraint=models.UniqueConstraint(fields=('user', 'date'), name='fe_unique_daily_progress'),
        ),
    ]
