# Generated by Django 5.2.3 on 2026-09-08 23:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fe', '0005_progress_tables'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(blank=True, max_length=60, verbose_name='小分類')),
                ('title', models.CharField(max_length=120, verbose_name='見出し')),
                ('body', models.TextField(verbose_name='本文')),
                ('source', models.CharField(blank=True, max_length=120, verbose_name='出典')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notes', to='fe.category', verbose_name='中分類')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fe_notes', to=settings.AUTH_USER_MODEL, verbose_name='所有者')),
            ],
            options={
                'verbose_name': 'FE 技術解説',
                'verbose_name_plural': 'FE 技術解説',
                'ordering': ['category__code', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LearningRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('A', '科目A'), ('B', '科目B')], default='A', max_length=1, verbose_name='科目')),
                ('reading_seconds', models.PositiveIntegerField(verbose_name='提示時間(秒)')),
                ('phase', models.CharField(choices=[('reading', '解説を読む'), ('quiz', '解答する'), ('done', '終了')], default='reading', max_length=10, verbose_name='段階')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='解答中の位置')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='開始日時')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='終了日時')),
                ('note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rounds', to='fe.learningnote', verbose_name='読んだ解説')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fe_rounds', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'FE 学習ラウンド',
                'verbose_name_plural': 'FE 学習ラウンド',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='LearningItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(verbose_name='出題順')),
                ('selected_index', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='選んだ選択肢')),
                ('is_correct', models.BooleanField(blank=True, null=True, verbose_name='正誤')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_items', to='fe.question', verbose_name='問題')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='fe.learninground', verbose_name='ラウンド')),
            ],
            options={
                'verbose_name': 'FE 学習ラウンドの問題',
                'verbose_name_plural': 'FE 学習ラウンドの問題',
                'ordering': ['order'],
                'constraints': [models.UniqueConstraint(fields=('round', 'order'), name='fe_unique_round_order')],
            },
        ),
    ]
