# Generated by Django 5.2.3 on 2026-09-24 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fe', '0006_learningnote_learninground_learningitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='subject',
            field=models.CharField(choices=[('A', '科目A'), ('B', '科目B')], default='A', max_length=1, verbose_name='科目'),
        ),
        migrations.AlterField(
            model_name='category',
            name='code',
            field=models.PositiveSmallIntegerField(unique=True, verbose_name='分類番号'),
        ),
        migrations.AlterField(
            model_name='category',
            name='exam_weight',
            field=models.PositiveSmallIntegerField(verbose_name='想定出題数'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=40, verbose_name='分類'),
        ),
    ]
