# Generated by Django 5.2.3 on 2026-09-25 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fe', '0007_category_subject_alter_category_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PassReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passed_on', models.DateField(verbose_name='合格した試験の受験日')),
                ('reported_at', models.DateTimeField(auto_now_add=True, verbose_name='申告日時')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fe_pass_report', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'FE 合格の申告',
                'verbose_name_plural': 'FE 合格の申告',
                'ordering': ['-passed_on'],
            },
        ),
    ]
