# Generated by Django 5.2.3 on 2025-07-13 13:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sepal_length', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)], verbose_name='がく片の長さ (cm)')),
                ('sepal_width', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)], verbose_name='がく片の幅 (cm)')),
                ('petal_length', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)], verbose_name='花弁の長さ (cm)')),
                ('petal_width', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)], verbose_name='花弁の幅 (cm)')),
                ('prediction', models.CharField(max_length=50, verbose_name='予測結果')),
                ('probability', models.FloatField(verbose_name='予測確率')),
                ('model_used', models.CharField(default='RandomForest', max_length=100, verbose_name='使用モデル')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': '予測履歴',
                'verbose_name_plural': '予測履歴',
                'ordering': ['-created_at'],
            },
        ),
    ]
