# Generated by Django 5.2.3 on 2026-10-04 06:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveSmallIntegerField(unique=True, verbose_name='分類番号')),
                ('name', models.CharField(max_length=40, verbose_name='分類')),
                ('subject', models.CharField(choices=[('A', '科目A'), ('B', '科目B')], default='A', max_length=1, verbose_name='科目')),
                ('field', models.CharField(choices=[('T', 'テクノロジ系'), ('M', 'マネジメント系'), ('S', 'ストラテジ系')], max_length=1, verbose_name='分野')),
                ('major_code', models.PositiveSmallIntegerField(verbose_name='大分類番号')),
                ('major_name', models.CharField(max_length=40, verbose_name='大分類')),
                ('exam_weight', models.PositiveSmallIntegerField(verbose_name='想定出題数')),
            ],
            options={
                'verbose_name': 'AP 中分類',
                'verbose_name_plural': 'AP 中分類',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Learner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^[a-z0-9_-]{3,30}$', 'ID は半角の英小文字・数字・「_」「-」で、3〜30文字にしてください。')], verbose_name='ID')),
                ('is_admin', models.BooleanField(default=False, help_text='問題集の取り込み・書き出しと、問題の一覧ができる。', verbose_name='管理用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
            ],
            options={
                'verbose_name': 'AP 学習者ID',
                'verbose_name_plural': 'AP 学習者ID',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='LearningNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(blank=True, max_length=60, verbose_name='小分類')),
                ('title', models.CharField(max_length=120, verbose_name='見出し')),
                ('body', models.TextField(verbose_name='本文')),
                ('source', models.CharField(blank=True, max_length=120, verbose_name='出典')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notes', to='ap.category', verbose_name='中分類')),
            ],
            options={
                'verbose_name': 'AP 技術解説',
                'verbose_name_plural': 'AP 技術解説',
                'ordering': ['category__code', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LearningRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('A', '科目A'), ('B', '科目B')], default='A', max_length=1, verbose_name='科目')),
                ('reading_seconds', models.PositiveIntegerField(verbose_name='提示時間(秒)')),
                ('phase', models.CharField(choices=[('reading', '解説を読む'), ('quiz', '解答する'), ('done', '終了')], default='reading', max_length=10, verbose_name='段階')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='解答中の位置')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='開始日時')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='終了日時')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='ap.learner', verbose_name='ID')),
                ('note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rounds', to='ap.learningnote', verbose_name='読んだ解説')),
            ],
            options={
                'verbose_name': 'AP 学習ラウンド',
                'verbose_name_plural': 'AP 学習ラウンド',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='PassReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passed_on', models.DateField(verbose_name='合格した試験の受験日')),
                ('reported_at', models.DateTimeField(auto_now_add=True, verbose_name='申告日時')),
                ('learner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pass_report', to='ap.learner', verbose_name='ID')),
            ],
            options={
                'verbose_name': 'AP 合格の申告',
                'verbose_name_plural': 'AP 合格の申告',
                'ordering': ['-passed_on'],
            },
        ),
        migrations.CreateModel(
            name='QuestionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True, verbose_name='テンプレートキー')),
                ('title', models.CharField(max_length=100, verbose_name='題材')),
                ('topic', models.CharField(blank=True, max_length=60, verbose_name='小分類')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='templates', to='ap.category', verbose_name='中分類')),
            ],
            options={
                'verbose_name': 'AP 問題テンプレート',
                'verbose_name_plural': 'AP 問題テンプレート',
                'ordering': ['category__code', 'key'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('A', '科目A'), ('B', '科目B')], default='A', max_length=1, verbose_name='科目')),
                ('topic', models.CharField(blank=True, max_length=60, verbose_name='小分類')),
                ('stem', models.TextField(verbose_name='問題文')),
                ('choices', models.JSONField(verbose_name='選択肢')),
                ('answer_index', models.PositiveSmallIntegerField(verbose_name='正解の選択肢番号（0始まり）')),
                ('explanation', models.TextField(blank=True, verbose_name='解説')),
                ('difficulty', models.PositiveSmallIntegerField(choices=[(1, '基本'), (2, '標準'), (3, '応用')], default=2, verbose_name='難易度')),
                ('source', models.CharField(blank=True, max_length=120, verbose_name='出典・根拠')),
                ('params', models.JSONField(blank=True, null=True, verbose_name='生成パラメータ')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='ap.category', verbose_name='中分類')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='ap.questiontemplate', verbose_name='生成元テンプレート')),
            ],
            options={
                'verbose_name': 'AP 問題',
                'verbose_name_plural': 'AP 問題',
                'ordering': ['category__code', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('focus', 'おまかせ（苦手を重点出題）'), ('random', '本番の出題比率どおり'), ('weak', '苦手分野だけ'), ('review', '間違えた問題の復習'), ('category', '分野を指定')], default='focus', max_length=10, verbose_name='出題モード')),
                ('subject', models.CharField(choices=[('A', '科目A'), ('B', '科目B')], default='A', max_length=1, verbose_name='科目')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ap.category', verbose_name='指定中分類')),
                ('learner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='study_session', to='ap.learner', verbose_name='ID')),
            ],
            options={
                'verbose_name': 'AP 出題設定',
                'verbose_name_plural': 'AP 出題設定',
            },
        ),
        migrations.CreateModel(
            name='DailyProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日付')),
                ('answered', models.PositiveIntegerField(default=0, verbose_name='解答数')),
                ('correct', models.PositiveIntegerField(default=0, verbose_name='正解数')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_progress', to='ap.learner', verbose_name='ID')),
            ],
            options={
                'verbose_name': 'AP 日別の学習記録',
                'verbose_name_plural': 'AP 日別の学習記録',
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('learner', 'date'), name='ap_unique_daily_progress')],
            },
        ),
        migrations.CreateModel(
            name='CategoryProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('A', '科目A'), ('B', '科目B')], default='A', max_length=1, verbose_name='科目')),
                ('answered', models.PositiveIntegerField(default=0, verbose_name='解答数')),
                ('correct', models.PositiveIntegerField(default=0, verbose_name='正解数')),
                ('last_answered_at', models.DateTimeField(blank=True, null=True, verbose_name='最終解答日時')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='progress', to='ap.category', verbose_name='中分類')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='ap.learner', verbose_name='ID')),
            ],
            options={
                'verbose_name': 'AP 分野別の理解度',
                'verbose_name_plural': 'AP 分野別の理解度',
                'ordering': ['category__code'],
                'constraints': [models.UniqueConstraint(fields=('learner', 'category', 'subject'), name='ap_unique_progress')],
            },
        ),
        migrations.CreateModel(
            name='LearningItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(verbose_name='出題順')),
                ('selected_index', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='選んだ選択肢')),
                ('is_correct', models.BooleanField(blank=True, null=True, verbose_name='正誤')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ap.learninground', verbose_name='ラウンド')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_items', to='ap.question', verbose_name='問題')),
            ],
            options={
                'verbose_name': 'AP 学習ラウンドの問題',
                'verbose_name_plural': 'AP 学習ラウンドの問題',
                'ordering': ['order'],
                'constraints': [models.UniqueConstraint(fields=('round', 'order'), name='ap_unique_round_order')],
            },
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_index', models.PositiveSmallIntegerField(verbose_name='選んだ選択肢')),
                ('is_correct', models.BooleanField(verbose_name='正誤')),
                ('elapsed_ms', models.PositiveIntegerField(blank=True, null=True, verbose_name='所要時間(ms)')),
                ('answered_at', models.DateTimeField(auto_now_add=True, verbose_name='解答日時')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='ap.category', verbose_name='中分類')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='ap.learner', verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='ap.question', verbose_name='問題')),
            ],
            options={
                'verbose_name': 'AP 解答ログ',
                'verbose_name_plural': 'AP 解答ログ',
                'ordering': ['-answered_at'],
                'indexes': [models.Index(fields=['learner', '-answered_at'], name='ap_attempt_learner_at_idx'), models.Index(fields=['learner', 'category'], name='ap_attempt_learner_cat_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['subject', 'category'], name='ap_question_subj_cat_idx'),
        ),
    ]
