# Generated by Django 5.2.3 on 2026-10-07 13:14

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='learner',
            name='last_seen_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='最終利用日時'),
        ),
        migrations.AlterField(
            model_name='learner',
            name='code',
            field=models.CharField(blank=True, help_text='空のときは、履歴を残さずに使っている一時的な記録。', max_length=30, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[a-z0-9_-]{3,30}$', 'ID は半角の英小文字・数字・「_」「-」で、3〜30文字にしてください。')], verbose_name='ID'),
        ),
    ]
